name: stepy
description: A Step Counter App written in Flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1
  shared_preferences: ^2.0.15
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  flex_color_scheme: ^6.0.1
  json_annotation: ^4.7.0
  intl: ^0.17.0
  workmanager: ^0.5.1
  pedometer:
    git:
      url: https://github.com/LootExe/Pedometer.git

  foreground: 
    git:
      url: https://github.com/LootExe/Foreground.git
#    path: D:/_Daten/Flutter/foreground/
    
  permission_handler: ^10.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fading_edge_scrollview: ^3.0.0
  flutter_speed_dial: ^6.2.0
          
dev_dependencies:
#  flutter_test:
#    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.22.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  flutter_launcher_icons: ^0.11.0
  path: ^1.8.2
  hive_generator: ^2.0.0
  
flutter:
  uses-material-design: true
  assets:
    - asset/google_fonts/
    - asset/icon/
  fonts:
    - family: CustomIcons
      fonts:
      - asset: asset/CustomIcons.ttf

flutter_icons:
  android: true
  image_path: 'asset/icon/launcher_icon.png'
